import express from 'express';
console.log('Express imported');
import cors from 'cors';
console.log('CORS imported');
import helmet from 'helmet';
console.log('Helmet imported');
import dotenv from 'dotenv';
console.log('Dotenv imported');
import path from 'path';
console.log('Path imported');
import prisma from './src/lib/prisma.js';
console.log('Prisma imported');
import authRoutes from './src/routes/auth.js';
console.log('Auth routes imported');
import aiRoutes from './src/routes/ai.js';
console.log('AI routes imported');
import jobsRoutes from './src/routes/jobs.js';
console.log('Jobs routes imported');
import qualificationsRoutes from './src/routes/qualifications.js';
console.log('Qualifications routes imported');
import documentsRoutes from './src/routes/documents.js';
console.log('Documents routes imported');
import usersRoutes from './src/routes/users.js';
console.log('Users routes imported');
import coursesRoutes from './src/routes/courses.js';
console.log('Courses routes imported');
import settingsRoutes from './src/routes/settings.js';
console.log('Settings routes imported');
import contactRoutes from './src/routes/contact.js';
console.log('Contact routes imported');
import certificateRoutes from './src/routes/certificates.js';
console.log('Certificates routes imported');
import enrollmentRoutes from './src/routes/enrollments.js';
console.log('Enrollments routes imported');
import notificationRoutes from './src/routes/notifications.js';
console.log('Notifications routes imported');
import analyticsRoutes from './src/routes/analytics.js';
console.log('Analytics routes imported');
import wishlistRoutes from './src/routes/wishlist.js';
console.log('Wishlist routes imported');
import pointsRoutes from './src/routes/points.js';
console.log('Points routes imported');
import referralRoutes from './src/routes/referrals.js';
console.log('Referral routes imported');
import partnerRoutes from './src/routes/partners.js';
console.log('Partner routes imported');
import { initializeScheduler } from './src/services/syncScheduler.js';
console.log('Scheduler imported');

console.log('ALL IMPORTS SUCCESSFUL');
